# SPDX-FileCopyrightText: 2024 Piras314 <92357316+Piras314@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2025 LaCumbiaDelCoronavirus <90893484+LaCumbiaDelCoronavirus@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 SX-7 <sn1.test.preria.2002@gmail.com>
# SPDX-FileCopyrightText: 2025 github-actions[bot] <github-actions[bot]@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
# From https://github.com/DeltaV-Station/Delta-v/
name: PR Changelogs
concurrency: commit_action
on:
  pull_request_target:
    types: [closed]

env:
  CHANGELOG_DIR: ${{ vars.CHANGELOG_DIR }}
  CHANGELOG_TARGET_BRANCH: ${{ vars.CHANGELOG_TARGET_BRANCH }}
  PR_NUMBER: ${{ github.event.number }}

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    steps:
      - name: Checkout changelog branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: "${{ vars.CHANGELOG_TARGET_BRANCH }}"

      - name: Setup Git
        run: |
          git config --global user.name "${{ vars.BOT_USER }}"
          git config --global user.email "${{ vars.BOT_EMAIL }}"

      - name: Setup Node and Install Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Resolve Dependencies and Generate Changelog
        run: |
          cd Tools/changelog
          npm install --prefer-offline --no-audit --progress=false
          node changelog.js
        shell: bash

      - name: Commit Changelog
        run: |
          git add "$CHANGELOG_DIR"/*.yml
          git diff --cached --quiet || git commit -m "${{ vars.CHANGELOG_MESSAGE }} (#${{ env.PR_NUMBER }})"
          git push
        shell: bash
